Double-Owner/ReVibe

- src/main/java/com/doubleowner/revibe/domain/user/controller/UserController.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/request/UserSignupRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/response/UserSignupResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/Role.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/repository/UserRepository.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
> [BE][feat] 회원가입 기능 구현

- src/main/java/com/doubleowner/revibe/domain/brand/repository/BrandRepository.java
- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/response/ItemResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Category.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Item.java
- src/main/java/com/doubleowner/revibe/domain/item/repository/ItemRepository.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
- src/main/java/com/doubleowner/revibe/global/config/WebConfig.java
> [BE][feat] 상품 등록 기능 구현

- src/main/java/com/doubleowner/revibe/domain/brand/controller/BrandController.java
- src/main/java/com/doubleowner/revibe/domain/brand/dto/BrandRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/brand/dto/BrandResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/brand/entity/Brand.java
- src/main/java/com/doubleowner/revibe/domain/brand/service/BrandService.java
> [BE][feat] 브랜드 등록 기능 구현

- src/main/java/com/doubleowner/revibe/domain/account/controller/AccountController.java
- src/main/java/com/doubleowner/revibe/domain/account/dto/AccountRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/account/dto/AccountResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/account/entity/Account.java
- src/main/java/com/doubleowner/revibe/domain/account/service/AccountService.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/repository/UserRepository.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
> [BE][feat] 사용자 계좌 기능 구현

- src/main/java/com/doubleowner/revibe/domain/account/service/AccountService.java
- src/main/java/com/doubleowner/revibe/domain/user/controller/UserController.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/request/UserDeleteRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/UserStatus.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
- src/main/java/com/doubleowner/revibe/global/config/WebConfig.java
> [BE][feat] 회원 삭제 기능

- src/main/java/com/doubleowner/revibe/domain/user/controller/UserController.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/request/UserProfileUpdateRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/response/UserProfileResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
> [BE][feat] 회원 프로필 수정 기능 구현

- src/main/java/com/doubleowner/revibe/domain/user/controller/UserController.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
> [BE][feat] 회원 프로필 조회 기능 구현

- src/main/java/com/doubleowner/revibe/domain/payment/controller/PaymentController.java
- src/main/java/com/doubleowner/revibe/domain/payment/dto/CardPaymentRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/payment/dto/PaymentResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/payment/entity/PayMethod.java
- src/main/java/com/doubleowner/revibe/domain/payment/entity/Payment.java
- src/main/java/com/doubleowner/revibe/domain/payment/repository/PaymentRepository.java
- src/main/java/com/doubleowner/revibe/domain/payment/service/PaymentService.java
> [BE][feat] 카드 결제 기능 구현

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemUpdateRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Item.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
> [BE][feat] 상품 수정 기능 구현

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
> [BE][feat] 상품 조회 기능 구현

- src/main/java/com/doubleowner/revibe/domain/review/controller/ReviewController.java
- src/main/java/com/doubleowner/revibe/domain/review/dto/ReviewRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/review/dto/ReviewResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/review/entity/Review.java
- src/main/java/com/doubleowner/revibe/domain/review/repository/ReviewRepository.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
- src/main/java/com/doubleowner/revibe/global/config/S3Config.java
- src/main/java/com/doubleowner/revibe/global/util/S3Uploader.java
> [BE][feat] 리뷰 작성(이미지 작성 포함) 기능 구현

- src/main/java/com/doubleowner/revibe/domain/payment/service/PaymentService.java
cardPaymentRequestDto.getBuybidId()) -> cardPaymentRequestDto.getBuyBidId())
> [BE][mod] PaymentService 변수명 수정

- src/main/java/com/doubleowner/revibe/domain/cart/controller/CartController.java
- src/main/java/com/doubleowner/revibe/domain/cart/dto/request/CartRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/cart/dto/response/CartResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/cart/entity/Cart.java
- src/main/java/com/doubleowner/revibe/domain/cart/repository/CartRepository.java
- src/main/java/com/doubleowner/revibe/domain/cart/service/CartService.java
- src/main/java/com/doubleowner/revibe/global/config/WebConfig.java
> [BE][feat] 장바구니 기능 구현

- src/main/java/com/doubleowner/revibe/domain/review/controller/ReviewController.java
- src/main/java/com/doubleowner/revibe/domain/review/entity/Review.java
- src/main/java/com/doubleowner/revibe/domain/review/repository/ReviewRepository.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
[BE][feat] 사용자 별 리뷰 조회 기능 구현 #30
> [BE][feat] 사용자 별 리뷰 조회 기능 구현

- src/main/java/com/doubleowner/revibe/domain/review/controller/ReviewController.java
- src/main/java/com/doubleowner/revibe/domain/review/dto/UpdateReviewRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/review/entity/Review.java
- src/main/java/com/doubleowner/revibe/domain/review/repository/ReviewRepository.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
[BE][feat] 사용자 별 리뷰 수정 기능 구현 #31
> [BE][feat] 사용자 별 리뷰 수정 기능 구현

- src/main/java/com/doubleowner/revibe/domain/review/controller/ReviewController.java
- src/main/java/com/doubleowner/revibe/domain/review/dto/UpdateReviewRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/review/entity/Review.java
- src/main/java/com/doubleowner/revibe/domain/review/repository/ReviewRepository.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
[BE][feat] 사용자 별 리뷰 삭제 기능 구현 #32
> [BE][feat] 사용자 별 리뷰 삭제 기능 구현

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemUpdateRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Item.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
- src/main/java/com/doubleowner/revibe/global/util/S3Uploader.java
#45 [BE][feat] 상품 등록,수정 이미지 추가 기능 구현
> [BE][feat] 상품 등록,수정 이미지 추가 기능 구현

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/global/config/S3Config.java
[BE][chore] 상품 수정 및 이미지 기능 오타 수정
> [BE][chore] 상품 수정 및 이미지 기능 오타 수정

- build.gradle
- src/main/java/com/doubleowner/revibe/global/config/SecurityConfig.java
- src/main/java/com/doubleowner/revibe/global/config/WebConfig.java
- src/main/java/com/doubleowner/revibe/global/kakao/controller/KOAuthController.java
- src/main/java/com/doubleowner/revibe/global/kakao/service/OAuth2UserService.java
- src/main/java/com/doubleowner/revibe/global/util/JwtProvider.java
> [BE][feat] 카카오 소셜로그인 accessToken 요청 및 전달

- src/main/java/com/doubleowner/revibe/global/kakao/controller/KOAuthController.java
- src/main/java/com/doubleowner/revibe/global/kakao/service/OAuth2UserService.java
> [BE][refactor] accessToken 발급

- src/main/java/com/doubleowner/revibe/domain/user/dto/response/UserProfileResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/response/UserSignupResponseDto.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/LoginMethod.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/repository/UserRepository.java
- src/main/java/com/doubleowner/revibe/global/kakao/controller/KOAuthController.java
- src/main/java/com/doubleowner/revibe/global/kakao/dto/KOAuthResponseDto.java
- src/main/java/com/doubleowner/revibe/global/kakao/service/OAuth2UserService.java
> [BE][feat] 카카오 소셜 로그인 사용자 정보

- src/main/java/com/doubleowner/revibe/domain/user/controller/UserController.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/request/UserProfileUpdateRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/user/dto/request/UserSignupRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/user/entity/User.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
> [BE][add] 사용자 프로필이미지 기능 추가

- src/main/java/com/doubleowner/revibe/domain/account/service/AccountService.java
- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
- src/main/java/com/doubleowner/revibe/global/exception/AccountException.java
- src/main/java/com/doubleowner/revibe/global/exception/GlobalExceptionHandler.java
- src/main/java/com/doubleowner/revibe/global/exception/UserException.java
- src/main/java/com/doubleowner/revibe/global/exception/errorCode/AccountErrorCode.java
- src/main/java/com/doubleowner/revibe/global/exception/errorCode/UserErrorCode.java
> [BE][refactor] 사용자 서비스 예외처리

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
> [BE][mod] 상품 검색기능 수정

- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
> [BE][chore] 리뷰 예외 수정

- src/main/java/com/doubleowner/revibe/domain/user/service/UserService.java
- src/main/java/com/doubleowner/revibe/global/config/dto/JwtAuthResponse.java
- src/main/java/com/doubleowner/revibe/global/kakao/service/OAuth2UserService.java
#78
refresh 토큰 발행 -> 추후 redis 연동
> [BE][feat] refresh 토큰 발행

- src/main/java/com/doubleowner/revibe/domain/brand/repository/BrandRepository.java
- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Item.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
- src/main/java/com/doubleowner/revibe/domain/wishlist/service/WishlistService.java
- src/main/java/com/doubleowner/revibe/global/common/service/ImageService.java
[BE][refactor] 상품생성, 이미지 관련 리펙토링
> [BE][refactor] 상품생성, 이미지 관련 리펙토링

- src/main/java/com/doubleowner/revibe/domain/option/entity/Option.java
- src/main/java/com/doubleowner/revibe/domain/sellbid/service/SellBidService.java
[BE][feat] 판매입찰 시 옵션 수량 증가 및 동시성제어
> [BE][feat] 판매입찰 시 옵션 수량 증가 및 동시성제어

- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
- src/main/java/com/doubleowner/revibe/global/common/service/ImageService.java
- src/main/java/com/doubleowner/revibe/global/util/S3Uploader.java
[BE][mod] 이미지 삭제에 한글 깨짐으로 인한 오류수정
> [BE][mod] 이미지 삭제에 한글 깨짐으로 인한 오류수정

- src/main/java/com/doubleowner/revibe/domain/item/dto/request/ItemRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/item/entity/Item.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
[BE][refactor] 상품 등록 builder적용
> [BE][refactor] 상품 등록 builder적용

- src/main/java/com/doubleowner/revibe/domain/review/dto/ReviewRequestDto.java
- src/main/java/com/doubleowner/revibe/domain/review/entity/Review.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
[BE][refactor] toEntity(),toDto()메서드 추출
> [BE][refactor] toEntity(),toDto()메서드 추출

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
> [BE][refactor] 상품 조회 Slice 적용

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/domain/item/repository/ItemRepositoryQuery.java
- src/main/java/com/doubleowner/revibe/domain/item/repository/ItemRepositoryQueryImpl.java
- src/main/java/com/doubleowner/revibe/domain/item/service/ItemService.java
- src/main/java/com/doubleowner/revibe/global/config/RedisCacheConfig.java
[BE][add] 상품 목록 첫화면 캐시 적용 및 불필요한 COUNT 쿼리 삭제 #143
> [BE][add] 상품 목록 첫화면 캐시 적용 및 불필요한 COUNT 쿼리 삭제

- src/main/java/com/doubleowner/revibe/domain/review/controller/ReviewController.java
- src/main/java/com/doubleowner/revibe/domain/review/repository/ReviewRepository.java
- src/main/java/com/doubleowner/revibe/domain/review/service/ReviewService.java
[BE][mod] 엔티티 관계 변경에 따른 조회 기능 수정
> [BE][mod] 엔티티 관계 변경에 따른 조회 기능 수정

- src/main/java/com/doubleowner/revibe/domain/item/controller/ItemController.java
- src/main/java/com/doubleowner/revibe/global/config/WebConfig.java
> [BE][mod] 권한 경로 설정 2차

- src/main/java/com/doubleowner/revibe/domain/like/controller/LikeController.java
- src/main/java/com/doubleowner/revibe/domain/like/service/LikeService.java
> [BE][refactor] 좋아요 기능 URI 변경

- src/main/java/com/doubleowner/revibe/global/aop/LockAspect.java
> [BE][add] spel 파서 적용 추가

- src/main/java/com/doubleowner/revibe/global/config/CorsConfig.java
> [BE][test] 배포 테스트
